AllCops:
  TargetRubyVersion: 2.6

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentArray:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/WordArray:
  MinSize: 3
