= API仕様書

電子ペーパーとの通信でのAPIについて説明します。FMV-DPPL2でのみ確認しています。

== 基本仕様

=== 接続形式

どの接続であってもネットワーク通信になっており、全てのプロトコルは HTTP/1.1 です。APIによって使える接続方式が異なります。「接続」はそれぞれ次の意味です。

[horizontal]
USB:: USB接続 (Ethernet over USB)
Blootooth:: Blootooth接続 (現在未確認)
HTTP:: ネットワーク(Wi-Fi)を通じて、8080ポートへHTTP通信
HTTPS:: ネットワーク(Wi-Fi)を通じて、8443ポートへHTTPS通信(暗号化)

HTTPSで使用される証明書はアプリケーションインストール時に信頼済みストアにインストールされます。証明書のホスト名は"digitalpaper.local"に固定のため、複数の機器がある場合、証明書のホスト名(CN)とmDNSで取得するホスト名が一致するとは限りません。

=== 認証

HTTPS接続は/auth系を除いて資格情報のクッキーが必須です。クッキーは常に更新されていきますので、HTTPS通信時はクッキーを管理したクライアントが必要になります。最初の資格情報は/auth系を用いた認証そりで取得します。

=== コンテンツ

APIとの通信時のデータのやり取りは原則JSONを用いて行われます。エンコードはUTF-8です。機器側のWebサーバーアプリケーションはRestlet-Frameworkです。

ファイルの送受信を除き、PUT/POSTの要求およびGET/POSTの応答のコンテンツはUTF-8のJSONです。

Content-Type:: application/json; charset=UTF-8

=== 日時表示

日時表示は二種類あります。ECMAScriptでの処理を前提にしているため、それに添った形式になっています。

ISO 8601日時形式:: ECMAScriptで定められたISO 8601拡張フォーマットの日時形式です。タイムゾーンはUTCで固定(常にZ)で、ミリ秒は表記しません。`YYYY-MM-DDTHH:mm:ssZ`と言う形になります。strftime形式の場合は`%Y-%m-%dT%H:%M:%SZ`です。
UNIX時間ミリ秒:: UNIXエポックから経過**ミリ秒**です。ECMAScriptにおけるDateオブジェクトのvalueと同じになります。閏秒は無視されます。多くのUNIX時間とは違いミリ秒であることに注意してください。(特に、ECMAScript以外で処理する場合は注意が必要)

=== エントリー

エントリーはファイルまたはディレクトリ(フォルダ)です。一意のIDで管理されています。トップディレクトリのIDは`root`で固定です。それ以外はUUID形式で管理されています。

== API

バージョン 1.3 対応しています。ファームウェアアップデート等でAPIのバージョンがあがった場合は対応できない場合があります。

=== GET /register/serial_number

機器のシリアル番号を取得します。

==== 要求

[horizontal]
メソッド:: GET
パス:: /register/serial_number
接続:: USB, HTTP
認証:: 不要

==== 応答

.JSON
[horizontal]
value:: 機器のシリアル番号文字列

=== GET /register/information

機器の基本情報(モデル名等)を取得します。

==== 要求

[horizontal]
メソッド:: GET
パス:: /register/information
接続:: USB, HTTP
認証:: 不要

==== 応答

.JSON
[horizontal]
device_color:: デバイスの色 CSSカラー形式 現行は白(`"#ffffff"`)のみ
model_name:: モデル名 FMV-DPP02は `"P02"`
serial_number:: 機器のシリアル番号文字列
sku_code:: 言語コード？？？ 日本語では `"J"` 。

=== GET /api_version

APIのバージョンを取得します。現在のバージョンは 1.3 です。

==== 要求

[horizontal]
メソッド:: GET
パス:: /api_version
接続:: USB, HTTP, HTTPS
認証:: 不要

.クエリ
[horizontal]
_:: (オプション) POSIXタイムのミリ秒(接続開始したときの時刻)

==== 応答

.JSON
[horizontal]
value:: APIバージョン 現在は `"1.3"`

=== POST /register/pin

(調査中)

==== 要求

[horizontal]
メソッド:: POST
パス:: /register/pin
接続:: USB
認証:: (不明)

==== 応答

(不明)

=== POST /register/hash

(調査中)

==== 要求

[horizontal]
メソッド:: POST
パス:: /register/hash
接続:: USB
認証:: (不明)

==== 応答

(不明)

=== POST /register/ca

(調査中)

==== 要求

[horizontal]
メソッド:: POST
パス:: /register/ca
接続:: USB
認証:: (不明)

==== 応答

(不明)

=== POST /register

(調査中)

==== 要求

[horizontal]
メソッド:: POST
パス:: /register
接続:: USB
認証:: (不明)

==== 応答

(不明)

=== PUT /register/cleanup

(調査中)

==== 要求

[horizontal]
メソッド:: PUT
パス:: /register/cleanup
接続:: USB
認証:: (不明)

==== 応答

(不明)

=== GET /ping

(調査中)

==== 要求

[horizontal]
メソッド:: GET
パス:: /ping
接続:: HTTPS
認証:: 必要

==== 応答

(不明)

== GET /auth/nonce/%UUID%

==== 要求

[horizontal]
メソッド:: GET
パス:: `/auth/nonce/%UUID%`
接続:: HTTPS

`%UUID%` はdeviceid.datに書かれているUUID

==== 応答

.JSON
[horizontal]
nonce:: ノンス(64バイトASCII文字列)

ノンスは `/^[A-Za-z0-9+\/]{64}$/` であるため、暗号論的に安全に生成した48バイトの乱数をBase64でエンコードしていることによって得ていると思われます。しかし、秘密鍵による署名の際は、デコードせずにそのまま文字列データとして扱います。

== PUT /auth

==== 要求

Origin: file://

.JSON
[horizontal]
cliend_id:: `/auth/nonce/%UUID%` で指定したUUID
nonce_signed:: 秘密鍵によるノンスの署名(改行無しのBase64エンコード)

**ノンスはデコードしません。**ハッシュアルゴリズムにはSHA256を使用し、クライアントの秘密鍵で署名します。Rubyで書いた場合、 `Base64.strict_encode64(pkey.sign('sha256', nonce))` となります。

==== 応答

.Cookie
[horizontal]
Credentials:: 資格情報(64バイトASCII文字列)
Domain:: `digitalpaper.local`
Path:: `/`
Secure:: 有効

資格情報は `/^[A-Za-z0-9+\/]{64}$/` であるため、暗号論的に安全に生成した48バイトの乱数をBase64でエンコードしていることによって得ていると思われます。

=== PUT /system/configs/datetime

日時を設定します。

Origin: file://

[horizontal]
value:: UTCでのXMLスキーマ sprintfにおける"%Y-%m-%dT%H:%M:%SZ"

==== 応答

無し

== GET /system/configs

=== 要求

.クエリ
[horizontal]
_:: POSIXタイムのミリ秒(接続開始したときの時刻)

=== 応答

[horizontal]
ステータス:: 200 OK
コンテンツ:: application/json; charset=UTF-8
クッキー設定:: あり

.JSON
[horizontal]
date_format::
  value::: 日付の表示形式 `"yyyy/M/d"` 等
initialized_flag::
  value::: 初期化済み化のフラグ `"initialized"` 等
owner::
  value::: 所有者の名前
time_format::
  value::: 時刻の表示形式 `"12hour"` 等
timeout_to_standby::
  value::: スリープまでの時間、単位は分？ `"60"` 等
timezone::
  value::: タイムゾーン JST(+9000)の場合は `"Asia/Tokyo"`


== GET /folders/%エントリーID%/entries

%エントリーID%にはエントリーIDが入ります。トップディレクトリは`root`で固定です。それ以外は取得したエントリーIDが入ります。

ルートディレクトリのパスは"Document"となります。エントリーのパスはそこからの絶対パスです。

=== 要求

.クエリ
[horizontal]
order_type:: 表示順 デフォルトは `entry_name_asc`
offset:: リストのオフセット 最初は `0`
limit:: リストのエントリー最大数 `50`
_:: POSIXタイムのミリ秒(接続開始したときの時刻)

=== 応答

エントリーのパスは `Document/` から始まります。

.JSON
[horizontal]
count:: エントリーの個数
entry_list_hash:: エントリーリストのハッシュ値 ID.リビジョン.0
entry_list:: エントリーのリスト、下記の形式がエントリー配列として並ぶ
  created_date::: エントリーの作成日時 IOS 8601日時形式
  entry_id::: エントリーのID UUID形式 (rootを除く)
  entry_name::: エントリーの名前 例: `"Samples"`
  entry_path::: エントリーのパス 例: `"Document/Samples"`
  entry_type::: エントリーの種類 ディレクトリは`"folder"
  is_new::: 新規化のフラグ `"false"`
  parent_folder_id::: 親ディレクトリのID

=== GET /documents/%エントリーID%

=== GET /documents/%エントリーID%/file

=== GET /resolve/entry/%エントリーパス%

== その他の応答

=== 認証失敗

[horizontal]
ステータス:: 401 Unauthorized

.JSON
[horizontal]
error_code:: `"40100"`
message:: `"Authentication is required."`
